module.exports = {
  introduction: "/react/introduction/",
  webpack: "/webpack/introduction/",
  webpack_compared: "/webpack/appendices/comparison/",
  developing_with_webpack: "/webpack/developing/",
  webpack_and_react: "/webpack/output/server-side-rendering/",
  react: "/react/getting-started/",
  implementing_notes: "/react/getting-started/implementing-notes/",
  react_and_flux: "/react/implementing-kanban/react-and-flux/",
  from_notes_to_kanban: "/react/implementing-kanban/from-notes-to-kanban/",
  implementing_dnd: "/react/implementing-kanban/drag-and-drop/",
  building_kanban: "/webpack/building/",
  advanced: "/react/advanced-techniques/",
  testing_react: "/react/advanced-techniques/testing-react/",
  typing_with_react: "/react/advanced-techniques/typing-with-react/",
  linting_in_webpack: "/maintenance/code-quality/linting/",
  authoring_libraries: "/maintenance/packaging/",
  styling_react: "/react/advanced-techniques/styling-react/",
  appendices: "/react/appendices/",
  structuring_react_projects:
    "/react/advanced-techniques/structuring-react-projects/",
  language_features: "/react/appendices/language-features/",
  understanding_decorators: "/react/appendices/understanding-decorators/",
  troubleshooting: "/react/appendices/troubleshooting/",
};
